<?php

namespace SaltHareket\Theme;

use MatthiasMullie\Minify\JS as JSMinifier;

/**
 * AssetPacker - CSS ve JS dosyalarını birleştirir, minify eder ve akıllıca cache'ler.
 * Mükerrer bundle oluşumunu engellemek için dosya listesini stabilize eder.
 */
class AssetPacker {
    private $files = [];
    private $type;
    private $output_name;
    private $cache_dir;
    private $cache_url;

    /**
     * @param array  $files       Path listesi, Handle listesi veya [] (Otomatik Tema Ayıklama)
     * @param string $type        'css' veya 'js'
     * @param string $output_name Dosya adı ön eki (Örn: 'main-bundle')
     */
    public function __construct(array $files = [], string $type = 'css', string $output_name = 'bundle') {
        $this->type = strtolower($type);
        $this->output_name = $output_name;
        
        $this->cache_dir = STATIC_PATH . "cache/";
        $this->cache_url = STATIC_URL . "cache/";

        // 1. Dosyaları Topla
        if (empty($files)) {
            $this->files = $this->collect_wp_assets([], true);
        } elseif (strpos($files[0], '/') === false) {
            $this->files = $this->collect_wp_assets($files, false);
        } else {
            $this->files = $files;
        }

        // 2. Mükerrerliği Engelle: Dosya listesini alfabetik sırala. 
        // Böylece farklı sayfalarda aynı dosyalar gelse bile hash hep aynı çıkar.
        sort($this->files);

        if (!is_dir($this->cache_dir)) {
            mkdir($this->cache_dir, 0755, true);
        }
    }

    /**
     * WordPress Registry içinden sadece ilgili dosyaları çeker.
     */
    private function collect_wp_assets(array $filter_handles = [], bool $only_theme_assets = false) {
        global $wp_styles, $wp_scripts;
        $paths = [];
        $wp_registry = ($this->type === 'css') ? $wp_styles : $wp_scripts;

        if ($wp_registry && isset($wp_registry->registered)) {
            $theme_folder = get_template(); 
            $loop_target = !empty($filter_handles) ? $filter_handles : array_keys($wp_registry->registered);

            foreach ($loop_target as $handle) {
                if (isset($wp_registry->registered[$handle])) {
                    $obj = $wp_registry->registered[$handle];
                    if (!$obj->src) continue;

                    $url = $obj->src;

                    // Otomatik Ayıklama: Sadece tema klasöründekileri al
                    if ($only_theme_assets && strpos($url, $theme_folder) === false) {
                        continue;
                    }

                    if (!preg_match('/^(https?:)?\/\//', $url)) {
                        $url = site_url($url);
                    }

                    $path = str_replace(site_url('/'), ABSPATH, $url);
                    if (file_exists($path)) {
                        $paths[] = $path;
                    }
                }
            }
        }
        return array_unique($paths);
    }

    /**
     * Dosya tarihlerinden eşsiz bir HASH üretir (Buna URL dahil edilmez)
     */
    private function generate_hash() {
        $data = "";
        foreach ($this->files as $file) {
            if (file_exists($file)) {
                $data .= $file . filemtime($file);
            }
        }
        return substr(md5($data), 0, 12);
    }

    /**
     * Birleşmiş dosyanın URL'ini verir. Dosya yoksa oluşturur.
     */
    public function get_url() {
        if (empty($this->files)) return "";

        $combined_hash = $this->generate_hash();
        $final_filename = $this->output_name . "-" . $combined_hash . "." . $this->type;
        $file_path = $this->cache_dir . $final_filename;
        $file_url = $this->cache_url . $final_filename;

        if (file_exists($file_path)) {
            return $file_url;
        }

        return $this->pack($file_path) ? $file_url : "";
    }

    /**
     * Birleştirme ve Minify işlemini yapar.
     */
    private function pack($save_path) {
        if (empty($this->files)) return false;

        $header = "/* Generated by AssetPacker | Files: " . count($this->files) . " | Date: " . date('Y-m-d H:i:s') . " */" . PHP_EOL;

        if ($this->type === 'css') {
            // CSS: MergeCSS ile mükerrer selectorleri temizle ve MİNİFY ET
            $merger = new \SaltHareket\Theme\MergeCSS($this->files, $save_path, true, false);
            $merger->run();

            if (file_exists($save_path)) {
                $content = file_get_contents($save_path);
                return file_put_contents($save_path, $header . $content) !== false;
            }
        } else {
            // JS: JSMinifier ile birleştir ve küçült
            $minifier = new JSMinifier();
            foreach ($this->files as $file) {
                if (file_exists($file)) {
                    $minifier->add($file);
                }
            }
            $minifier->minify($save_path);
            
            if (file_exists($save_path)) {
                $content = file_get_contents($save_path);
                return file_put_contents($save_path, $header . $content) !== false;
            }
        }
        return false;
    }
}