$ = jQuery.noConflict();
jQuery(document).ready(function($){
if(typeof acf!=='undefined'){(function($){function initialize_bs_columns_field($field){if($($field).closest(".wp-block").data("type")=="acf/bootstrap-columns"){let block=$($field).closest(".wp-block");let row_cols=block.find("[data-name='row_cols']").first();let breakpoints=block.find("[data-name='acf_block_columns']").first().find(".values").first().find(">.layout").not("[data-layout='block-bootstrap-columns']").find("[data-name='breakpoints']");row_cols.find("input[type='checkbox']").on("change",function(){console.log(breakpoints.length)
if($(this).is(":checked")){breakpoints.addClass("acf-hidden")}else{breakpoints.removeClass("acf-hidden")}});acf.add_action('acfe/modal/open',function($modal,$args){let breakpoints=$($modal.$el).find("[data-name='breakpoints']").first();let row_cols=$($modal.$el).closest(".acf-block-fields").find("[data-name='row_cols']").first();if(row_cols.find("input[type='checkbox']").is(":checked")){breakpoints.addClass("acf-hidden")}else{breakpoints.removeClass("acf-hidden")}})}}
if(typeof acf.add_action!=='undefined'){acf.add_action('ready_field/type=acf_bs_breakpoints',initialize_bs_columns_field);acf.add_action('append_field/type=acf_bs_breakpoints',initialize_bs_columns_field)}})(jQuery)}
if(typeof acf!=='undefined'){(function($){$(document).on('click','.acf-file-uploader .acf-icon.-cancel',function(){const fileInput=$(this).closest('.acf-file-uploader').find('input[type="hidden"]');fileInput.val('')})})(jQuery)}
function acfGalleryHeight(){if($(".acf-field.acf-field-gallery").length>0){$(".acf-field.acf-field-gallery").each(function(){if($(this).find('.acf-gallery-attachments').children().length==0){$(this).find(".acf-gallery.ui-resizable").css("height","0px")}else{$(this).find(".acf-gallery.ui-resizable").css("height","400px")}})}}
document.addEventListener('click',function(){setTimeout(function(){acfGalleryHeight()},1000)});acfGalleryHeight()
if(typeof acf!=='undefined'){(function($){function initialize_post_type_field($field){var name=$field.data("name");var select=$field.find("select");var parent=$field.closest(".acf-row");switch(name){case "menu_item_post_type":var chained_name="menu_item_taxonomy";break}
var chained=parent.find("[data-name='"+chained_name+"']");if(chained.length>0){$field.find("select").off("change").on("change",function(e){var target=jQuery(e.target);var post_type=parent.find("[data-name='menu_item_post_type']").find("select").val();var value=$(this).val();if(!IsBlank(value)){$(this).closest(".acf-field").attr("data-val",value)}
var selected=chained.attr("data-val");selected=IsBlank(selected)?"":selected;chained.addClass("loading-process");chained.find("select").empty();if(!value){return}
var data={action:'get_post_type_taxonomies',post_type:post_type,name:name,value:value,selected:selected,post_id:acf.get('post_id'),}
data=acf.prepareForAjax(data);this.request=$.ajax({url:acf.get('ajaxurl'),data:data,type:"post",dataType:'json',success:function(json){if(!json){return}
if(json.error){chained.removeClass("loading-process");chained.addClass("d-none");alert(json.message)}else{chained.removeClass("loading-process")
if(!IsBlank(json.html)){chained.find("select").html(json.html);if(["menu_item_post_type","menu_item_taxonomy"].includes(name)){chained.find("select").trigger("change")}}}}})}).trigger("change")}}
if(typeof acf.add_action!=='undefined'){jQuery("[data-name='menu_populate']").find("[data-name='menu_item_post_type']").each(function(){initialize_post_type_field(jQuery(this));acf.add_action('ready_field/name=menu_item_post_type',initialize_post_type_field);acf.add_action('append_field/name=menu_item_post_type',initialize_post_type_field)})}})(jQuery)}
if(typeof acf!=='undefined'){function updateUniqueSelect($repeater){var $repeater_obj=acf.getField($repeater.data("key"));var $select=$repeater.find(".unique select");var $maxItems=$select.find("option").length;$repeater_obj.$el.on('change','.unique select',function(){$repeater.find('.unique select option').prop("disabled",!1).removeClass("d-none");$repeater.find('.acf-row:not(.acf-clone)').each(function(){var $currentRow=$(this);var $currentSelect=$currentRow.find('.unique select');var selectedValue=$currentSelect.val();if(selectedValue){$repeater.find('.unique select option[value="'+selectedValue+'"]:not(:selected)').prop("disabled",!0).addClass("d-none")}})}).on('click','.acf-repeater-add-row',function(){var rows=$repeater.find('.acf-row:not(.acf-clone)');debugJS(rows)
var $newRow=$(this).closest(".acf-repeater").find(".acf-row:last-child");var selectedOptions=[];rows.each(function(){var $currentRow=$(this);var $currentSelect=$currentRow.find('.unique select');var selectedValue=$currentSelect.val();if(selectedValue){selectedOptions.push(selectedValue)}});$newRow.find('.unique select option').prop("disabled",!1).removeClass("d-none");$newRow.find('.unique select option').each(function(){var optionValue=$(this).val();if(selectedOptions.includes(optionValue)){$(this).prop("disabled",!0)}});$newRow.find('.unique select option:not(:disabled)').first().prop("selected",!0).removeClass("d-none");var currentItems=rows.length;if(currentItems>=$maxItems){$repeater_obj.$el.find('.acf-repeater-add-row').addClass('disabled')}else{$repeater_obj.$el.find('.acf-repeater-add-row').removeClass('disabled')}
$newRow.find('.unique select').trigger('change')});var key=$select.closest(".acf-field").data("key");acf.addAction('remove_field/key='+key,function(item){$repeater.find('.unique select option').prop("disabled",!1).removeClass("d-none");var rows=$repeater.find('.acf-row:not(.acf-clone)');var $deletedRow=item.$el.closest('.acf-row');var deletedRowSelectedValue=item.$el.find('.unique select').val();if(deletedRowSelectedValue){rows.each(function(){var $currentRow=$(this);var $currentSelect=$currentRow.find('.unique select');var selectedValue=$currentSelect.val();if(selectedValue&&selectedValue!==deletedRowSelectedValue){$repeater.find('.unique select option[value="'+selectedValue+'"]').prop("disabled",!0).addClass("d-none")}})}else{rows.each(function(){var $currentRow=$(this);var $currentSelect=$currentRow.find('.unique select');var selectedValue=$currentSelect.val();if(selectedValue){var $otherRowSelect=$deletedRow.siblings('.acf-row').find('.unique select');var otherSelectedValue=$otherRowSelect.val();if(selectedValue===otherSelectedValue){$repeater.find('.unique select option[value="'+selectedValue+'"]').prop("disabled",!0).addClass("d-none")}}})}})}
var unique_field=$(".acf-field-repeater .acf-row.acf-clone").find(".unique select");if(unique_field.length>0){unique_field.each(function(){var $repeater=$(this).closest(".acf-field-repeater");updateUniqueSelect($repeater)})}}
(function(){if(typeof tinymce!=="undefined"){tinymce.PluginManager.add('letter_spacing_button',function(editor,url){editor.addButton('letter_spacing_button',{text:'Letter Spacing',icon:!1,onclick:function(){var spacingValue=prompt('Enter the letter-spacing value (e.g. 2px):');if(spacingValue!==null){editor.formatter.apply('letter_spacing',{value:spacingValue})}}});editor.formatter.register('letter_spacing',{inline:'span',styles:{'letter-spacing':'%value'},remove_similar:!0})})}})()
function IsBlank(txt){var stat=!1;if(typeof(txt)==="undefined"||txt==null||txt=="null"||txt==undefined||txt=="undefined"||txt==""){stat=!0};return stat};function synchronize_child_and_parent_category($){$('.categorychecklist').find('input').each(function(index,input){$(input).bind('change',function(){var checkbox=$(this);var is_checked=$(checkbox).is(':checked');if(is_checked){$(checkbox).closest(".categorychecklist").find('input').not($(checkbox)).removeAttr('checked');$(checkbox).parents('li').children('label').children('input').attr('checked','checked')}else{$(checkbox).parentsUntil('ul').find('input').removeAttr('checked')}})})}
function updateDonutChart(el,percent,donut){percent=Math.round(percent);if(percent>100){percent=100}else if(percent<0){percent=0}
var deg=Math.round(360*(percent/100));if(percent>50){el.find('.pie').css('clip','rect(auto, auto, auto, auto)');el.find('.right-side').css('transform','rotate(180deg)')}else{el.find('.pie').css('clip','rect(0, 1em, 1em, 0.5em)');el.find('.right-side').css('transform','rotate(0deg)')}
if(donut){el.find('.right-side').css('border-width','0.1em');el.find('.left-side').css('border-width','0.1em');el.find('.shadow').css('border-width','0.1em')}else{el.find('.right-side').css('border-width','0.5em');el.find('.left-side').css('border-width','0.5em');el.find('.shadow').css('border-width','0.5em')}
el.find('.left-side').css('transform','rotate('+deg+'deg)')}
function get_star_rating_readonly($stars,$value,$count,$star_front,$star_back){$stars=parseInt($stars);$stars=IsBlank($stars)||isNaN($stars)?5:$stars;$value=parseFloat($value);if(typeof $count==="undefined"){$count=""}else{if($count>0){$count='<span class="count">('+$count+')</span>'}else{$count=""}}
var $className="";if($value==0){$className=" not-reviewed "}
$value=IsBlank($value)||isNaN($value)?0:$value;$star_front=IsBlank($star_front)?"fas fa-star":$star_front;$star_back=IsBlank($star_back)?"fas fa-star":$star_back;var $percentage=(100*$value)/$stars;var $code='<div class="star-rating star-rating-readonly '+$className+'" title="'+$value+'">'+'<div class="back">';for($i=1;$i<=$stars;$i++){$code+='<i class="'+$star_back+'" aria-hidden="true"></i>'};$code+='<div class="front" style="width:'+$percentage+'%;">';for($i=1;$i<=$stars;$i++){$code+='<i class="'+$star_front+'" aria-hidden="true"></i>'};$code+='</div>'+'</div>'+'<div class="sum">'+$value.toFixed(1)+$count+'</div>'+'</div>';return $code}
function text2clipboard(){$('.clipboard').each(function(){$(this).addClass("user-select-none").wrapInner("<span class='p-1 rounded-2'/>")})
$('.clipboard').click(function(){$(this).find("span").css("background-color","#ddd");var textToCopy=$(this).text();var tempTextarea=$('<textarea>');$('body').append(tempTextarea);tempTextarea.val(textToCopy).select();document.execCommand('copy');tempTextarea.remove();$(this).find("span").animate({backgroundColor:"transparent"},1000,function(){})})}
function header_tools_condition($el){$el=$el||{};var data={"languages":["dropdown","inactive","all"],"favorites":["offcanvas","dropdown"],"messages":["offcanvas","dropdown"],"notifications":["offcanvas","dropdown"],"cart":["offcanvas","dropdown"],"user-menu":["offcanvas","dropdown"],"navigation":["offcanvas"],"search":["offcanvas"]};if($el.length>0){var menu_item=$el.find(".acf-field[data-name='menu_item']")}else{var menu_item=$(".acf-field[data-name='menu_item']")}
if(menu_item.length>0){menu_item.not(".header-tools-inited").each(function(){$(this).addClass("header-tools-inited");$(this).find('select').on('change',function(){var val=$(this).val();var menu_type=$(this).closest(".acf-row").find(".acf-field[data-name='menu_type']");var menu_type_val=menu_type.find('select option:selected').val();if(data.hasOwnProperty(val)){menu_type.find('select option').addClass("d-none");for(var i=0;i<data[val].length;i++){var type=data[val][i];menu_type.find('select option[value="'+type+'"]').removeClass("d-none")}}else{menu_type.find('select option').removeClass("d-none")}
menu_type.find("select option").prop('selected',!1);if(menu_type_val==""){menu_type.find("select option").not(".d-none").first().prop('selected',!0)}else{menu_type.find("select option[value='"+menu_type_val+"']").not(".d-none").prop('selected',!0)}
menu_type.trigger("change");debugJS(val)
debugJS(menu_type)
debugJS(menu_type_val)
debugJS(menu_type.find("select"));debugJS(menu_type.find("select option").not(".d-none").first())}).trigger("change")})}}(function($){if($(".acf-repeater-add-row").length>0){if(!window.location.search.includes('page=header'))return;$(".acf-repeater-add-row").on("click",function(){debugJS("add row klik")
var obj=$(this);setTimeout(function(){header_tools_condition(obj.closest(".acf-repeater").find(".acf-row").not(".acf-clone"))},1500)})
header_tools_condition($(".acf-repeater").find(".acf-row").not(".acf-clone"))}})(jQuery)
text2clipboard()
jQuery(document).ready(function($){if(typeof L!=='undefined'&&typeof map!=='undefined'){setTimeout(function(){map.invalidateSize()},100);$(window).on('resize',function(){map.invalidateSize()})}})
jQuery(document).ready(function($){$('#publish').on('click',function(e){var language=$('#wp-admin-bar-languages > .ab-item > .ab-label').attr("lang");if(language&&typenow==""){var confirmMessage='Eğer sayfayı kaydederseniz bu optionlar '+language+' sayfası için ayarlanacaktır. Emin misiniz?';if(!confirm(confirmMessage)){e.preventDefault()}}})})
if(typeof acf!=='undefined'){acf.addAction('select2_init',function($select,args,settings,field){var field_name=field.$el.data("name");if(field_name=="notification_event"){$select.find("option").each(function(){let option=jQuery(this);let text=option.text().split("|");option.text(text[0]);option.attr("data-description",text[1])});args.templateResult=function(state){debugJS(state);if(!state.id){return state.text}else{let title=state.text;let description=$(state.element).data("description");let $state='<div><strong>'+title+'</strong></div><div style="font-size:12px;color:#888;">'+description+'</div>'
return jQuery($state)}};$select.select2(args)}})}
if($(".star-rating-readonly-ui").length>0){$(".star-rating-readonly-ui").each(function(){var stars=$(this).data("stars")||5;var value=$(this).data("value");$(this).html(get_star_rating_readonly(stars,value,"","",""))})}
jQuery(document).ready(function($){setTimeout(function(){if(typeof tinymce!=="undefined"&&typeof qTranslateConfig!=="undefined"){var editor=tinymce.get('description');if(editor){var content=editor.getContent();var content=content.replace(/^<p>|<\/p>$/g,'');var regex=/\[:([a-z]+)]([^\[:]+)(?=\[|$)/g;var result={};var match;while((match=regex.exec(content))!==null){var lang=match[1];var value=match[2];result[lang]=value}
var languages=qTranslateConfig.language_config;var lang_active=qTranslateConfig.activeLanguage;var keys=Object.keys(languages);for(var item in result){$("input[name='qtranslate-fields[description]["+item+"]']").val(result[item])}
editor.setContent('');editor.execCommand('mceInsertContent',!1,result[lang_active])}}},100)})
});
