$ = jQuery.noConflict();
jQuery(document).ready(function($){
if(typeof acf!=='undefined'){(function($){function initialize_bs_columns_field($field){var $block=$($field).closest('.wp-block');if($block.data('type')!=='acf/bootstrap-columns')return;var $rowCols=$block.find("[data-name='row_cols']").first();var $breakpoints=$block.find("[data-name='acf_block_columns']").first().find('.values').first().find('> .layout').not("[data-layout='block-bootstrap-columns']").find("[data-name='breakpoints']");$rowCols.find("input[type='checkbox']").on('change',function(){$breakpoints.toggleClass('acf-hidden',$(this).is(':checked'))});acf.add_action('acfe/modal/open',function($modal){var $bp=$($modal.$el).find("[data-name='breakpoints']").first();var $rc=$($modal.$el).closest('.acf-block-fields').find("[data-name='row_cols']").first();$bp.toggleClass('acf-hidden',$rc.find("input[type='checkbox']").is(':checked'))})}
if(typeof acf.add_action!=='undefined'){acf.add_action('ready_field/type=acf_bs_breakpoints',initialize_bs_columns_field);acf.add_action('append_field/type=acf_bs_breakpoints',initialize_bs_columns_field)}})(jQuery)}
if(typeof acf!=='undefined'){(function($){$(document).on('click','.acf-file-uploader .acf-icon.-cancel',function(){$(this).closest('.acf-file-uploader').find('input[type="hidden"]').val('')})})(jQuery)}
function acfGalleryHeight(){$('.acf-field.acf-field-gallery').each(function(){var $gallery=$(this).find('.acf-gallery.ui-resizable');var hasItems=$(this).find('.acf-gallery-attachments').children().length>0;$gallery.css('height',hasItems?'400px':'0px')})}
document.addEventListener('click',function(){setTimeout(acfGalleryHeight,1000)});acfGalleryHeight()
if(typeof acf!=='undefined'){(function($){function initialize_post_type_field($field){var name=$field.data('name');var parent=$field.closest('.acf-row');var chained_name=(name==='menu_item_post_type')?'menu_item_taxonomy':null;if(!chained_name)return;var $chained=parent.find("[data-name='"+chained_name+"']");if(!$chained.length)return;$field.find('select').off('change').on('change',function(){var value=$(this).val();var post_type=parent.find("[data-name='menu_item_post_type'] select").val();var selected=$chained.attr('data-val')||'';if(value)$(this).closest('.acf-field').attr('data-val',value);$chained.addClass('loading-process').find('select').empty();if(!value)return;var data=acf.prepareForAjax({action:'get_post_type_taxonomies',post_type:post_type,name:name,value:value,selected:selected,post_id:acf.get('post_id')});$.ajax({url:acf.get('ajaxurl'),data:data,type:'post',dataType:'json',success:function(json){$chained.removeClass('loading-process');if(!json)return;if(json.error){$chained.addClass('d-none');alert(json.message);return}
if(json.html){$chained.find('select').html(json.html);if(['menu_item_post_type','menu_item_taxonomy'].indexOf(name)!==-1){$chained.find('select').trigger('change')}}}})}).trigger('change')}
if(typeof acf.add_action!=='undefined'){$("[data-name='menu_populate'] [data-name='menu_item_post_type']").each(function(){initialize_post_type_field($(this));acf.add_action('ready_field/name=menu_item_post_type',initialize_post_type_field);acf.add_action('append_field/name=menu_item_post_type',initialize_post_type_field)})}})(jQuery)}
if(typeof acf!=='undefined'){function updateUniqueSelect($repeater){var $field=acf.getField($repeater.data('key'));var $select=$repeater.find('.unique select');var maxItems=$select.find('option').length;function syncOptions(){$repeater.find('.unique select option').prop('disabled',!1).removeClass('d-none');$repeater.find('.acf-row:not(.acf-clone)').each(function(){var val=$(this).find('.unique select').val();if(val){$repeater.find('.unique select option[value="'+val+'"]:not(:selected)').prop('disabled',!0).addClass('d-none')}})}
$field.$el.on('change','.unique select',syncOptions);$field.$el.on('click','.acf-repeater-add-row',function(){var rows=$repeater.find('.acf-row:not(.acf-clone)');var $newRow=$(this).closest('.acf-repeater').find('.acf-row:last-child');var used=[];rows.each(function(){var v=$(this).find('.unique select').val();if(v)used.push(v);});$newRow.find('.unique select option').prop('disabled',!1).removeClass('d-none');$newRow.find('.unique select option').each(function(){if(used.indexOf($(this).val())!==-1)$(this).prop('disabled',!0);});$newRow.find('.unique select option:not(:disabled)').first().prop('selected',!0);var toggle=rows.length>=maxItems?'addClass':'removeClass';$field.$el.find('.acf-repeater-add-row')[toggle]('disabled');$newRow.find('.unique select').trigger('change')});var key=$select.closest('.acf-field').data('key');acf.addAction('remove_field/key='+key,function(){syncOptions()})}
var $unique=$('.acf-field-repeater .acf-row.acf-clone').find('.unique select');if($unique.length){$unique.each(function(){updateUniqueSelect($(this).closest('.acf-field-repeater'))})}}
(function(){if(typeof tinymce==='undefined')return;tinymce.PluginManager.add('letter_spacing_button',function(editor){editor.addButton('letter_spacing_button',{text:'Letter Spacing',icon:!1,onclick:function(){var val=prompt('Enter the letter-spacing value (e.g. 2px):');if(val!==null){editor.formatter.apply('letter_spacing',{value:val})}}});editor.formatter.register('letter_spacing',{inline:'span',styles:{'letter-spacing':'%value'},remove_similar:!0})})})()
function IsBlank(txt){return txt===undefined||txt===null||txt==='null'||txt==='undefined'||txt===''}
function synchronize_child_and_parent_category($){$('.categorychecklist').find('input').each(function(index,input){$(input).on('change',function(){var $cb=$(this);if($cb.is(':checked')){$cb.closest('.categorychecklist').find('input').not($cb).removeAttr('checked');$cb.parents('li').children('label').children('input').attr('checked','checked')}else{$cb.parentsUntil('ul').find('input').removeAttr('checked')}})})}
function updateDonutChart(el,percent,donut){percent=Math.max(0,Math.min(100,Math.round(percent)));var deg=Math.round(360*(percent/100));var bw=donut?'0.1em':'0.5em';if(percent>50){el.find('.pie').css('clip','rect(auto, auto, auto, auto)');el.find('.right-side').css('transform','rotate(180deg)')}else{el.find('.pie').css('clip','rect(0, 1em, 1em, 0.5em)');el.find('.right-side').css('transform','rotate(0deg)')}
el.find('.right-side, .left-side, .shadow').css('border-width',bw);el.find('.left-side').css('transform','rotate('+deg+'deg)')}
function get_star_rating_readonly($stars,$value,$count,$star_front,$star_back){$stars=parseInt($stars)||5;$value=parseFloat($value)||0;$star_front=$star_front||'fas fa-star';$star_back=$star_back||'fas fa-star';var countHtml='';if(typeof $count!=='undefined'&&$count>0){countHtml='<span class="count">('+$count+')</span>'}
var className=$value===0?' not-reviewed':'';var percentage=(100*$value)/$stars;var stars_back='',stars_front='';for(var i=0;i<$stars;i++){stars_back+='<i class="'+$star_back+'" aria-hidden="true"></i>';stars_front+='<i class="'+$star_front+'" aria-hidden="true"></i>'}
return'<div class="star-rating star-rating-readonly'+className+'" title="'+$value+'">'+'<div class="back">'+stars_back+'<div class="front" style="width:'+percentage+'%">'+stars_front+'</div>'+'</div>'+'<div class="sum">'+$value.toFixed(1)+countHtml+'</div>'+'</div>'}
function text2clipboard(){$('.clipboard').each(function(){$(this).addClass('user-select-none').wrapInner("<span class='p-1 rounded-2'/>")});$('.clipboard').on('click',function(){var $span=$(this).find('span');var text=$(this).text();$span.css('background-color','#ddd');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text)}else{var $tmp=$('<textarea>').appendTo('body').val(text).select();document.execCommand('copy');$tmp.remove()}
$span.animate({backgroundColor:'transparent'},1000)})}
function header_tools_condition($el){$el=$el||{};var config={'languages':['dropdown','inactive','all'],'favorites':['offcanvas','dropdown'],'messages':['offcanvas','dropdown'],'notifications':['offcanvas','dropdown'],'cart':['offcanvas','dropdown'],'user-menu':['offcanvas','dropdown'],'navigation':['offcanvas','dropdown'],'search':['offcanvas']};var menu_item=($el.length>0)?$el.find(".acf-field[data-name='menu_item']"):$(".acf-field[data-name='menu_item']");if(!menu_item.length)return;menu_item.not('.header-tools-inited').each(function(){$(this).addClass('header-tools-inited');$(this).find('select').on('change',function(){var val=$(this).val();var menu_type=$(this).closest('.acf-row').find(".acf-field[data-name='menu_type']");var prev_val=menu_type.find('select option:selected').val();var $options=menu_type.find('select option');if(config.hasOwnProperty(val)){$options.addClass('d-none');config[val].forEach(function(type){$options.filter('[value="'+type+'"]').removeClass('d-none')})}else{$options.removeClass('d-none')}
$options.prop('selected',!1);if(!prev_val){$options.not('.d-none').first().prop('selected',!0)}else{$options.filter('[value="'+prev_val+'"]').not('.d-none').prop('selected',!0)}
menu_type.trigger('change')}).trigger('change')})}(function($){if(!$('.acf-repeater-add-row').length)return;if(!window.location.search.includes('page=header'))return;$('.acf-repeater-add-row').on('click',function(){var obj=$(this);setTimeout(function(){header_tools_condition(obj.closest('.acf-repeater').find('.acf-row').not('.acf-clone'))},1500)});header_tools_condition($('.acf-repeater').find('.acf-row').not('.acf-clone'))})(jQuery)
text2clipboard()
jQuery(document).ready(function($){if(typeof L==='undefined'||typeof map==='undefined')return;setTimeout(function(){map.invalidateSize()},100);$(window).on('resize',function(){map.invalidateSize()})})
jQuery(document).ready(function($){$('#publish').on('click',function(e){var lang=$('#wp-admin-bar-languages > .ab-item > .ab-label').attr('lang');if(lang&&typeof typenow!=='undefined'&&typenow===''){if(!confirm('Bu optionlar '+lang+' sayfası için ayarlanacaktır. Emin misiniz?')){e.preventDefault()}}})})
if(typeof acf!=='undefined'){acf.addAction('select2_init',function($select,args,settings,field){if(field.$el.data('name')!=='notification_event')return;$select.find('option').each(function(){var $opt=jQuery(this);var parts=$opt.text().split('|');$opt.text(parts[0]);if(parts[1])$opt.attr('data-description',parts[1]);});args.templateResult=function(state){if(!state.id)return state.text;var desc=$(state.element).data('description')||'';return jQuery('<div><strong>'+state.text+'</strong></div>'+'<div style="font-size:12px;color:#888">'+desc+'</div>')};$select.select2(args)})}
if($('.star-rating-readonly-ui').length>0){$('.star-rating-readonly-ui').each(function(){var stars=$(this).data('stars')||5;var value=$(this).data('value')||0;$(this).html(get_star_rating_readonly(stars,value,'','',''))})}
jQuery(document).ready(function($){setTimeout(function(){if(typeof tinymce==='undefined'||typeof qTranslateConfig==='undefined')return;var editor=tinymce.get('description');if(!editor)return;var content=editor.getContent().replace(/^<p>|<\/p>$/g,'');var regex=/\[:([a-z]+)]([^\[:]+)(?=\[|$)/g;var result={};var match;while((match=regex.exec(content))!==null){result[match[1]]=match[2]}
var activeLang=qTranslateConfig.activeLanguage;for(var lang in result){$("input[name='qtranslate-fields[description]["+lang+"]']").val(result[lang])}
editor.setContent('');if(result[activeLang]){editor.execCommand('mceInsertContent',!1,result[activeLang])}},100)})
});
